/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardPermissionsRouteImport } from './routes/_authenticated.dashboard.permissions'
import { Route as AuthenticatedDashboardAppointmentsIndexRouteImport } from './routes/_authenticated.dashboard.appointments.index'
import { Route as AuthenticatedDashboardBillingIndexRouteImport } from './routes/_authenticated.dashboard.billing.index'
import { Route as AuthenticatedDashboardCrmIndexRouteImport } from './routes/_authenticated.dashboard.crm.index'
import { Route as AuthenticatedDashboardCustomersIndexRouteImport } from './routes/_authenticated.dashboard.customers.index'
import { Route as AuthenticatedDashboardExpensesIndexRouteImport } from './routes/_authenticated.dashboard.expenses.index'
import { Route as AuthenticatedDashboardInventoryIndexRouteImport } from './routes/_authenticated.dashboard.inventory.index'
import { Route as AuthenticatedDashboardInvoicesIndexRouteImport } from './routes/_authenticated.dashboard.invoices.index'
import { Route as AuthenticatedDashboardInvoicesIdRouteImport } from './routes/_authenticated.dashboard.invoices.$id'
import { Route as AuthenticatedDashboardModulesIndexRouteImport } from './routes/_authenticated.dashboard.modules.index'
import { Route as AuthenticatedDashboardReportsIndexRouteImport } from './routes/_authenticated.dashboard.reports.index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated.dashboard.settings.index'
import { Route as AuthenticatedDashboardStaffIndexRouteImport } from './routes/_authenticated.dashboard.staff.index'
import { Route as AuthenticatedDashboardSupportIndexRouteImport } from './routes/_authenticated.dashboard.support.index'
import { Route as AuthenticatedDashboardWebsiteIndexRouteImport } from './routes/_authenticated.dashboard.website.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPermissionsRoute =
  AuthenticatedDashboardPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAppointmentsIndexRoute =
  AuthenticatedDashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingIndexRoute =
  AuthenticatedDashboardBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCrmIndexRoute =
  AuthenticatedDashboardCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomersIndexRoute =
  AuthenticatedDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExpensesIndexRoute =
  AuthenticatedDashboardExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInventoryIndexRoute =
  AuthenticatedDashboardInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvoicesIndexRoute =
  AuthenticatedDashboardInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvoicesIdRoute =
  AuthenticatedDashboardInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardModulesIndexRoute =
  AuthenticatedDashboardModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsIndexRoute =
  AuthenticatedDashboardReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStaffIndexRoute =
  AuthenticatedDashboardStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportIndexRoute =
  AuthenticatedDashboardSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWebsiteIndexRoute =
  AuthenticatedDashboardWebsiteIndexRouteImport.update({
    id: '/website/',
    path: '/website/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/invoices/$id': typeof AuthenticatedDashboardInvoicesIdRoute
  '/dashboard/appointments/': typeof AuthenticatedDashboardAppointmentsIndexRoute
  '/dashboard/billing/': typeof AuthenticatedDashboardBillingIndexRoute
  '/dashboard/crm/': typeof AuthenticatedDashboardCrmIndexRoute
  '/dashboard/customers/': typeof AuthenticatedDashboardCustomersIndexRoute
  '/dashboard/expenses/': typeof AuthenticatedDashboardExpensesIndexRoute
  '/dashboard/inventory/': typeof AuthenticatedDashboardInventoryIndexRoute
  '/dashboard/invoices/': typeof AuthenticatedDashboardInvoicesIndexRoute
  '/dashboard/modules/': typeof AuthenticatedDashboardModulesIndexRoute
  '/dashboard/reports/': typeof AuthenticatedDashboardReportsIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/staff/': typeof AuthenticatedDashboardStaffIndexRoute
  '/dashboard/support/': typeof AuthenticatedDashboardSupportIndexRoute
  '/dashboard/website/': typeof AuthenticatedDashboardWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/invoices/$id': typeof AuthenticatedDashboardInvoicesIdRoute
  '/dashboard/appointments': typeof AuthenticatedDashboardAppointmentsIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingIndexRoute
  '/dashboard/crm': typeof AuthenticatedDashboardCrmIndexRoute
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersIndexRoute
  '/dashboard/expenses': typeof AuthenticatedDashboardExpensesIndexRoute
  '/dashboard/inventory': typeof AuthenticatedDashboardInventoryIndexRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesIndexRoute
  '/dashboard/modules': typeof AuthenticatedDashboardModulesIndexRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/staff': typeof AuthenticatedDashboardStaffIndexRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportIndexRoute
  '/dashboard/website': typeof AuthenticatedDashboardWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/invoices/$id': typeof AuthenticatedDashboardInvoicesIdRoute
  '/_authenticated/dashboard/appointments/': typeof AuthenticatedDashboardAppointmentsIndexRoute
  '/_authenticated/dashboard/billing/': typeof AuthenticatedDashboardBillingIndexRoute
  '/_authenticated/dashboard/crm/': typeof AuthenticatedDashboardCrmIndexRoute
  '/_authenticated/dashboard/customers/': typeof AuthenticatedDashboardCustomersIndexRoute
  '/_authenticated/dashboard/expenses/': typeof AuthenticatedDashboardExpensesIndexRoute
  '/_authenticated/dashboard/inventory/': typeof AuthenticatedDashboardInventoryIndexRoute
  '/_authenticated/dashboard/invoices/': typeof AuthenticatedDashboardInvoicesIndexRoute
  '/_authenticated/dashboard/modules/': typeof AuthenticatedDashboardModulesIndexRoute
  '/_authenticated/dashboard/reports/': typeof AuthenticatedDashboardReportsIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/dashboard/staff/': typeof AuthenticatedDashboardStaffIndexRoute
  '/_authenticated/dashboard/support/': typeof AuthenticatedDashboardSupportIndexRoute
  '/_authenticated/dashboard/website/': typeof AuthenticatedDashboardWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/onboarding'
    | '/blog/$slug'
    | '/store/$slug'
    | '/blog/'
    | '/dashboard/permissions'
    | '/dashboard/'
    | '/dashboard/invoices/$id'
    | '/dashboard/appointments/'
    | '/dashboard/billing/'
    | '/dashboard/crm/'
    | '/dashboard/customers/'
    | '/dashboard/expenses/'
    | '/dashboard/inventory/'
    | '/dashboard/invoices/'
    | '/dashboard/modules/'
    | '/dashboard/reports/'
    | '/dashboard/settings/'
    | '/dashboard/staff/'
    | '/dashboard/support/'
    | '/dashboard/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/onboarding'
    | '/blog/$slug'
    | '/store/$slug'
    | '/blog'
    | '/dashboard/permissions'
    | '/dashboard'
    | '/dashboard/invoices/$id'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/crm'
    | '/dashboard/customers'
    | '/dashboard/expenses'
    | '/dashboard/inventory'
    | '/dashboard/invoices'
    | '/dashboard/modules'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/support'
    | '/dashboard/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/blog/$slug'
    | '/store/$slug'
    | '/blog/'
    | '/_authenticated/dashboard/permissions'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/invoices/$id'
    | '/_authenticated/dashboard/appointments/'
    | '/_authenticated/dashboard/billing/'
    | '/_authenticated/dashboard/crm/'
    | '/_authenticated/dashboard/customers/'
    | '/_authenticated/dashboard/expenses/'
    | '/_authenticated/dashboard/inventory/'
    | '/_authenticated/dashboard/invoices/'
    | '/_authenticated/dashboard/modules/'
    | '/_authenticated/dashboard/reports/'
    | '/_authenticated/dashboard/settings/'
    | '/_authenticated/dashboard/staff/'
    | '/_authenticated/dashboard/support/'
    | '/_authenticated/dashboard/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/permissions': {
      id: '/_authenticated/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof AuthenticatedDashboardPermissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/appointments/': {
      id: '/_authenticated/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments/'
      preLoaderRoute: typeof AuthenticatedDashboardAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing/': {
      id: '/_authenticated/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof AuthenticatedDashboardBillingIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/crm/': {
      id: '/_authenticated/dashboard/crm/'
      path: '/crm'
      fullPath: '/dashboard/crm/'
      preLoaderRoute: typeof AuthenticatedDashboardCrmIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customers/': {
      id: '/_authenticated/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/expenses/': {
      id: '/_authenticated/dashboard/expenses/'
      path: '/expenses'
      fullPath: '/dashboard/expenses/'
      preLoaderRoute: typeof AuthenticatedDashboardExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inventory/': {
      id: '/_authenticated/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof AuthenticatedDashboardInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/invoices/': {
      id: '/_authenticated/dashboard/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof AuthenticatedDashboardInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/invoices/$id': {
      id: '/_authenticated/dashboard/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/dashboard/invoices/$id'
      preLoaderRoute: typeof AuthenticatedDashboardInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/modules/': {
      id: '/_authenticated/dashboard/modules/'
      path: '/modules'
      fullPath: '/dashboard/modules/'
      preLoaderRoute: typeof AuthenticatedDashboardModulesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports/': {
      id: '/_authenticated/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof AuthenticatedDashboardReportsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/staff/': {
      id: '/_authenticated/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof AuthenticatedDashboardStaffIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support/': {
      id: '/_authenticated/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support/'
      preLoaderRoute: typeof AuthenticatedDashboardSupportIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/website/': {
      id: '/_authenticated/dashboard/website/'
      path: '/website'
      fullPath: '/dashboard/website/'
      preLoaderRoute: typeof AuthenticatedDashboardWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardPermissionsRoute: typeof AuthenticatedDashboardPermissionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardInvoicesIdRoute: typeof AuthenticatedDashboardInvoicesIdRoute
  AuthenticatedDashboardAppointmentsIndexRoute: typeof AuthenticatedDashboardAppointmentsIndexRoute
  AuthenticatedDashboardBillingIndexRoute: typeof AuthenticatedDashboardBillingIndexRoute
  AuthenticatedDashboardCrmIndexRoute: typeof AuthenticatedDashboardCrmIndexRoute
  AuthenticatedDashboardCustomersIndexRoute: typeof AuthenticatedDashboardCustomersIndexRoute
  AuthenticatedDashboardExpensesIndexRoute: typeof AuthenticatedDashboardExpensesIndexRoute
  AuthenticatedDashboardInventoryIndexRoute: typeof AuthenticatedDashboardInventoryIndexRoute
  AuthenticatedDashboardInvoicesIndexRoute: typeof AuthenticatedDashboardInvoicesIndexRoute
  AuthenticatedDashboardModulesIndexRoute: typeof AuthenticatedDashboardModulesIndexRoute
  AuthenticatedDashboardReportsIndexRoute: typeof AuthenticatedDashboardReportsIndexRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
  AuthenticatedDashboardStaffIndexRoute: typeof AuthenticatedDashboardStaffIndexRoute
  AuthenticatedDashboardSupportIndexRoute: typeof AuthenticatedDashboardSupportIndexRoute
  AuthenticatedDashboardWebsiteIndexRoute: typeof AuthenticatedDashboardWebsiteIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardPermissionsRoute:
      AuthenticatedDashboardPermissionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardInvoicesIdRoute:
      AuthenticatedDashboardInvoicesIdRoute,
    AuthenticatedDashboardAppointmentsIndexRoute:
      AuthenticatedDashboardAppointmentsIndexRoute,
    AuthenticatedDashboardBillingIndexRoute:
      AuthenticatedDashboardBillingIndexRoute,
    AuthenticatedDashboardCrmIndexRoute: AuthenticatedDashboardCrmIndexRoute,
    AuthenticatedDashboardCustomersIndexRoute:
      AuthenticatedDashboardCustomersIndexRoute,
    AuthenticatedDashboardExpensesIndexRoute:
      AuthenticatedDashboardExpensesIndexRoute,
    AuthenticatedDashboardInventoryIndexRoute:
      AuthenticatedDashboardInventoryIndexRoute,
    AuthenticatedDashboardInvoicesIndexRoute:
      AuthenticatedDashboardInvoicesIndexRoute,
    AuthenticatedDashboardModulesIndexRoute:
      AuthenticatedDashboardModulesIndexRoute,
    AuthenticatedDashboardReportsIndexRoute:
      AuthenticatedDashboardReportsIndexRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
    AuthenticatedDashboardStaffIndexRoute:
      AuthenticatedDashboardStaffIndexRoute,
    AuthenticatedDashboardSupportIndexRoute:
      AuthenticatedDashboardSupportIndexRoute,
    AuthenticatedDashboardWebsiteIndexRoute:
      AuthenticatedDashboardWebsiteIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
