// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;
    let refreshToken: string | undefined;
    try {
      const { data, error } = await supabase.auth.getSession();
      if (error) {
        console.warn("attachSupabaseAuth getSession error:", error.message);
        await supabase.auth.signOut().catch(() => {});
      } else {
        token = data.session?.access_token;
        refreshToken = data.session?.refresh_token;
      }
    } catch (e) {
      console.error("attachSupabaseAuth failed:", e);
    }
    return next({
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(refreshToken ? { "x-refresh-token": refreshToken } : {}),
      },
    });
  },
);
